[package]
name = "nostr-rust-news"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
dist = { git = "https://github.com/junkpiano/Dist.git", package = "dist" }
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
