name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Check
        run: cargo check --all-targets

      - name: Test
        run: cargo test

      - name: Clippy
        run: cargo clippy -- -D warnings
